name: uriel_mainapp
description: Ghana's Premier EdTech Platform for BECE & WASSCE Preparation
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  google_sign_in: ^7.1.1
  cloud_firestore: ^6.0.0
  cloud_functions: ^6.0.0
  firebase_storage: ^13.0.0
  firebase_messaging: ^16.0.0
  provider: ^6.1.5
  http: ^1.4.0
  shared_preferences: ^2.5.3
  fl_chart: ^1.1.0
  url_launcher: ^6.3.1
  google_fonts: ^6.2.1
  share_plus: ^7.2.2
  image_picker: ^1.1.2
  epub_view: ^3.1.0
  flutter_tts: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/storybooks/
    - assets/storybook_covers/