name: uriel_mainapp
description: Ghana's Premier EdTech Platform for BECE & WASSCE Preparation
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  google_sign_in: ^7.1.1
  cloud_firestore: ^6.0.0
  cloud_functions: ^6.0.0
  firebase_storage: ^13.0.0
  firebase_messaging: ^16.0.0
  provider: ^6.1.5
  http: ^1.4.0
  shared_preferences: ^2.5.3
  path: ^1.8.2
  fl_chart: ^1.1.0
  url_launcher: ^6.3.1
  google_fonts: ^6.2.1
  share_plus: ^7.2.2
  image_picker: ^1.1.2
  epub_view: ^3.1.0
  flutter_tts: ^4.2.0
  epubx: ^4.0.0
  cached_network_image: ^3.3.0
  flutter_math_fork: ^0.7.2
  flutter_markdown: ^0.7.7+1
  uuid: ^4.4.0
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/notes_cover/creative_arts_note_cover.png
    - assets/notes_cover/english_note_cover.png
    - assets/notes_cover/french_note_cover.png
    - assets/notes_cover/ghanaian_language_note_cover.png
    - assets/notes_cover/ict_note_cover.png
    - assets/notes_cover/integrated_science_note_cover.png
    - assets/notes_cover/mathematics_note_cover.png
    - assets/notes_cover/rmw_note_cover.png
    - assets/notes_cover/social_studies_note_cover.png
    - assets/storybooks/
    - assets/storybook_covers/
    - assets/leaderboards_rank/
    - assets/trivia/
  # Added flutter_svg to support rendering packaged SVG assets for question figures