// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs7k7K9h8cMZ7gSYPeVR0DQuNbP9Hehtk',
    appId: '1:391331682365:android:1a76a8980691389de43254',
    messagingSenderId: '391331682365',
    projectId: 'uriel-academy-41fb0',
    storageBucket: 'uriel-academy-41fb0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNjzCfYVFw7atkos7Ic2HKJKe_y8bjHlM',
    appId: '1:391331682365:ios:37236cf49e675b25e43254',
    messagingSenderId: '391331682365',
    projectId: 'uriel-academy-41fb0',
    storageBucket: 'uriel-academy-41fb0.firebasestorage.app',
    iosClientId: '391331682365-mdtt3l67p1ler743dpleehm8rt3svms0.apps.googleusercontent.com',
    iosBundleId: 'com.example.urielMainapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNjzCfYVFw7atkos7Ic2HKJKe_y8bjHlM',
    appId: '1:391331682365:ios:37236cf49e675b25e43254',
    messagingSenderId: '391331682365',
    projectId: 'uriel-academy-41fb0',
    storageBucket: 'uriel-academy-41fb0.firebasestorage.app',
    iosClientId: '391331682365-mdtt3l67p1ler743dpleehm8rt3svms0.apps.googleusercontent.com',
    iosBundleId: 'com.example.urielMainapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw7s-BhLRn3vLMFg_ixQ_HrMAxLYSkyMw',
    appId: '1:391331682365:web:bdb1126fd5ff9b6be43254',
    messagingSenderId: '391331682365',
    projectId: 'uriel-academy-41fb0',
    authDomain: 'uriel-academy-41fb0.firebaseapp.com',
    storageBucket: 'uriel-academy-41fb0.firebasestorage.app',
    measurementId: 'G-BP8DM4YXLD',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw7s-BhLRn3vLMFg_ixQ_HrMAxLYSkyMw',
    appId: '1:391331682365:web:bdb1126fd5ff9b6be43254',
    messagingSenderId: '391331682365',
    projectId: 'uriel-academy-41fb0',
    authDomain: 'uriel-academy-41fb0.firebaseapp.com',
    storageBucket: 'uriel-academy-41fb0.firebasestorage.app',
    measurementId: 'G-BP8DM4YXLD',
  );

}
