import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import '../models/question_model.dart';
import '../models/question_collection_model.dart';
import '../services/question_service.dart';
import 'quiz_taker_page.dart';
import 'theory_year_questions_list.dart';

/// Page that displays past questions grouped as collections (e.g., "BECE RME 1999 MCQ")
/// This provides a much cleaner UI when there are hundreds of questions across multiple years
class QuestionCollectionsPage extends StatefulWidget {
  final String? initialSubject;

  const QuestionCollectionsPage({Key? key, this.initialSubject}) : super(key: key);

  @override
  State<QuestionCollectionsPage> createState() => _QuestionCollectionsPageState();
}

class _QuestionCollectionsPageState extends State<QuestionCollectionsPage> {
  final QuestionService _questionService = QuestionService();
  
  List<QuestionCollection> _collections = [];
  List<QuestionCollection> _filteredCollections = [];
  List<QuestionCollection> _loadedCollections = []; // For lazy loading
  bool _isLoading = false;
  bool _isLoadingMore = false; // For pagination loading
  bool _hasMoreCollections = true; // Track if more collections available
  bool _randomizeQuestions = false;
  // Map to track question count selection per collection
  final Map<String, int> _selectedQuestionCounts = {};
  // Pagination
  int _currentPage = 0;
  final int _pageSize = 20;
  final int _initialLoadSize = 12; // Load first 12 collections quickly
  
  // Filters
  String _selectedQuestionType = 'All Types'; // MCQ or Theory
  String _selectedSubject = 'All Subjects';
  String _selectedTopic = 'All Topics';
  String _selectedYear = 'All Years';
  final TextEditingController _searchController = TextEditingController();

  @override
  void initState() {
    super.initState();
    _loadCollections();
  }

  @override
  void dispose() {
    _searchController.dispose();
    super.dispose();
  }

  Future<void> _loadCollections() async {
    setState(() => _isLoading = true);
    try {
      debugPrint('🚀 Loading question collections with lazy loading...');
      
      // Load questions from main collection
      final mainQuestions = await _questionService.getQuestions(
        activeOnly: true,
      ).timeout(
        const Duration(seconds: 30),
        onTimeout: () {
          debugPrint('⏰ Timeout loading main questions after 30 seconds');
          return <Question>[];
        },
      );
      
      // Load French questions from separate collection
      final frenchQuestions = await _questionService.getQuestions(
        subject: Subject.french,
        activeOnly: true,
      ).timeout(
        const Duration(seconds: 30),
        onTimeout: () {
          debugPrint('⏰ Timeout loading French questions after 30 seconds');
          return <Question>[];
        },
      );
      
      // Combine all questions
      final allQuestions = [...mainQuestions, ...frenchQuestions];
      
      debugPrint('📊 Loaded ${mainQuestions.length} main questions and ${frenchQuestions.length} French questions (${allQuestions.length} total)');
      
      if (allQuestions.isEmpty) {
        debugPrint('⚠️ No questions loaded! Check Firebase connection and data.');
      }
      
      // Group into collections (auto-generated by year)
      final autoCollections = QuestionCollection.groupQuestions(allQuestions);
      
      // Sort by year (most recent first)
      autoCollections.sort((a, b) => b.year.compareTo(a.year));
      
      debugPrint('📦 Created ${autoCollections.length} auto-generated collections');
      
      // Load saved collections (e.g., ICT topic collections)
      final savedCollectionsData = await _questionService.getQuestionCollections(activeOnly: true);
      debugPrint('📚 Found ${savedCollectionsData.length} saved collections in Firestore');
      
      // Convert saved collections to QuestionCollection objects
      final savedCollections = <QuestionCollection>[];
      for (final collData in savedCollectionsData) {
        try {
          debugPrint('  Processing: ${collData['name'] ?? collData['id']}');
          final questionIds = List<String>.from(collData['questionIds'] ?? []);
          debugPrint('    Question IDs: ${questionIds.length}');
          
          if (questionIds.isEmpty) {
            debugPrint('    ⚠️ Skipping - no question IDs');
            continue;
          }
          
          final questions = await _questionService.getQuestionsByIds(questionIds);
          debugPrint('    Questions fetched: ${questions.length}');
          
          if (questions.isEmpty) {
            debugPrint('    ⚠️ Skipping - no questions fetched');
            continue;
          }
          
          if (questions.isNotEmpty) {
            // Parse subject from string
            final subjectStr = collData['subject'] ?? 'ict';
            Subject subject = Subject.ict;
            try {
              subject = Subject.values.firstWhere(
                (s) => s.name.toLowerCase() == subjectStr.toLowerCase(),
                orElse: () => Subject.ict,
              );
            } catch (e) {
              debugPrint('⚠️ Unknown subject: $subjectStr, defaulting to ICT');
            }
            
            // Parse exam type from string
            final examTypeStr = collData['examType'] ?? 'bece';
            ExamType examType = ExamType.bece;
            try {
              examType = ExamType.values.firstWhere(
                (e) => e.name.toLowerCase() == examTypeStr.toLowerCase(),
                orElse: () => ExamType.bece,
              );
            } catch (e) {
              debugPrint('⚠️ Unknown exam type: $examTypeStr, defaulting to BECE');
            }
            
            // Format title properly: BECE ICT [Topic Name]
            String title = collData['name'] ?? 'Unnamed Collection';
            // If it starts with 'ICT:', replace with 'BECE ICT'
            if (title.startsWith('ICT: ')) {
              title = 'BECE ICT ${title.substring(5)}';
            }
            
            final collection = QuestionCollection(
              id: collData['id'] ?? '',
              title: title,
              examType: examType,
              subject: subject,
              year: collData['year'] ?? 'All Years',
              questionType: questions.first.type,
              questionCount: questions.length,
              description: collData['topic'] ?? collData['description'], // Store topic in description for now
              questions: questions,
            );
            
            savedCollections.add(collection);
            debugPrint('✅ Loaded: ${collection.displayName} (${collection.questions.length} questions)');
          }
        } catch (e) {
          debugPrint('❌ Error loading collection ${collData['id']}: $e');
        }
      }
      
      // Merge auto and saved collections
      final allCollections = [...autoCollections, ...savedCollections];
      
      debugPrint('📦 Total collections: ${allCollections.length} (${autoCollections.length} auto + ${savedCollections.length} saved)');
      
      // Store all collections for lazy loading
      _collections = allCollections;
      
      // Load only first 12 collections initially for fast loading
      final initialCollections = allCollections.take(_initialLoadSize).toList();
      
      setState(() {
        _loadedCollections = initialCollections;
        _filteredCollections = initialCollections;
        _currentPage = 0; // reset pagination
        _isLoading = false;
        _hasMoreCollections = allCollections.length > _initialLoadSize;
      });
      
      // Apply initial subject filter if provided
      if (widget.initialSubject != null) {
        _applyInitialSubjectFilter();
      }
      
      // Load remaining collections in background
      if (_hasMoreCollections) {
        _loadRemainingCollectionsInBackground();
      }
      
    } catch (e) {
      debugPrint('❌ Error loading collections: $e');
      setState(() => _isLoading = false);
    }
  }

  // Load remaining collections in background without blocking UI
  void _loadRemainingCollectionsInBackground() {
    Future.delayed(const Duration(milliseconds: 100), () {
      if (mounted && _hasMoreCollections) {
        final remainingCollections = _collections.skip(_initialLoadSize).toList();
        setState(() {
          _loadedCollections.addAll(remainingCollections);
          _hasMoreCollections = false;
        });
        debugPrint('✅ All collections loaded in background (${remainingCollections.length} additional collections)');
      }
    });
  }

  // Load more collections when user clicks "Load More" button
  Future<void> _loadMoreCollections() async {
    if (_isLoadingMore || !_hasMoreCollections) return;

    setState(() => _isLoadingMore = true);

    // Simulate loading delay for smooth UX
    await Future.delayed(const Duration(milliseconds: 500));

    final nextPage = _currentPage + 1;
    final startIndex = (_currentPage * _pageSize);
    final endIndex = (nextPage * _pageSize);

    final moreCollections = _collections.skip(startIndex).take(_pageSize).toList();

    if (moreCollections.isNotEmpty) {
      setState(() {
        _loadedCollections.addAll(moreCollections);
        _currentPage = nextPage;
        _hasMoreCollections = endIndex < _collections.length;
      });
      debugPrint('📄 Loaded page $_currentPage: ${moreCollections.length} more collections');
    }

    setState(() => _isLoadingMore = false);
  }

  void _applyInitialSubjectFilter() {
    final subject = widget.initialSubject?.toLowerCase() ?? '';
    if (subject.contains('rme') || subject.contains('religious')) {
      setState(() {
        _selectedSubject = 'Religious and Moral Education';
        _applyFilters();
      });
    }
  }

  void _applyFilters() {
    setState(() {
      _currentPage = 0; // reset to first page when filters change
      _filteredCollections = _loadedCollections.where((collection) {
        // Question type filter (MCQ vs Theory)
        if (_selectedQuestionType != 'All Types') {
          final isMCQ = collection.questionType == QuestionType.multipleChoice;
          final isTheory = collection.questionType == QuestionType.essay;
          
          if (_selectedQuestionType == 'MCQ' && !isMCQ) return false;
          if (_selectedQuestionType == 'Theory' && !isTheory) return false;
        }
        
        // Subject filter
        if (_selectedSubject != 'All Subjects') {
          final subjectMatch = _formatSubjectName(collection.subject) == _selectedSubject;
          if (!subjectMatch) return false;
        }
        
        // Topic filter
        if (_selectedTopic != 'All Topics') {
          // Check collection-level topic (in description field for saved collections)
          bool hasCollectionTopic = collection.description == _selectedTopic;
          
          // Also check question-level topics
          final collectionTopics = collection.questions
              .expand((q) => q.topics)
              .toSet()
              .toList();
          bool hasQuestionTopic = collectionTopics.contains(_selectedTopic);
          
          if (!hasCollectionTopic && !hasQuestionTopic) return false;
        }
        
        // Year filter
        if (_selectedYear != 'All Years') {
          if (collection.year != _selectedYear) return false;
        }
        
        // Search filter
        if (_searchController.text.isNotEmpty) {
          final search = _searchController.text.toLowerCase();
          final displayText = (collection.title.isNotEmpty ? collection.title : collection.displayName).toLowerCase();
          if (!displayText.contains(search)) return false;
        }
        
        return true;
      }).toList();
    });
  }

  String _formatSubjectName(Subject subject) {
    switch (subject) {
      case Subject.mathematics: return 'Mathematics';
      case Subject.english: return 'English';
      case Subject.integratedScience: return 'Integrated Science';
      case Subject.socialStudies: return 'Social Studies';
      case Subject.ga: return 'Ga';
      case Subject.asanteTwi: return 'Asante Twi';
      case Subject.french: return 'French';
      case Subject.ict: return 'ICT';
      case Subject.religiousMoralEducation: return 'Religious and Moral Education';
      case Subject.creativeArts: return 'Creative Arts';
      case Subject.careerTechnology: return 'Career Technology';
      case Subject.trivia: return 'Trivia';
    }
  }

  @override
  Widget build(BuildContext context) {
    final isSmallScreen = MediaQuery.of(context).size.width < 768;
    
    return Scaffold(
      backgroundColor: const Color(0xFFF8FAFE),
      body: _isLoading
          ? const Center(child: CircularProgressIndicator(color: Color(0xFFD62828)))
          : CustomScrollView(
              slivers: [
                SliverToBoxAdapter(
                  child: _buildFilters(isSmallScreen),
                ),
                SliverToBoxAdapter(
                  child: _filteredCollections.isEmpty
                      ? _buildEmptyState()
                      : _buildCollectionsList(isSmallScreen),
                ),
              ],
            ),
    );
  }

  Widget _buildFilters(bool isSmallScreen) {
    return Container(
      margin: EdgeInsets.all(isSmallScreen ? 16 : 24),
      padding: EdgeInsets.all(isSmallScreen ? 16 : 20),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.05),
            blurRadius: 10,
            offset: const Offset(0, 2),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Title
          Text(
            'Search & Filter',
            style: GoogleFonts.playfairDisplay(
              fontSize: 18,
              fontWeight: FontWeight.bold,
              color: const Color(0xFF1A1E3F),
            ),
          ),
          const SizedBox(height: 16),
          // Search bar
          TextField(
            controller: _searchController,
            onChanged: (_) => _applyFilters(),
            style: GoogleFonts.montserrat(color: const Color(0xFF1A1E3F)),
            decoration: InputDecoration(
              hintText: 'Search collections...',
              hintStyle: GoogleFonts.montserrat(color: Colors.grey[400]),
              prefixIcon: Icon(Icons.search, color: Colors.grey[600]),
              filled: true,
              fillColor: const Color(0xFFF8FAFE),
              border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(12),
                borderSide: BorderSide.none,
              ),
              contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
            ),
          ),
          const SizedBox(height: 12),
          // Filter dropdowns
          if (isSmallScreen)
            Column(
              children: [
                _buildFilterDropdown('Question Type', _selectedQuestionType, ['All Types', 'MCQ', 'Theory'], (value) {
                  setState(() => _selectedQuestionType = value!);
                  _applyFilters();
                }),
                const SizedBox(height: 8),
                _buildFilterDropdown('Subject', _selectedSubject, _getSubjectOptions(), (value) {
                  setState(() {
                    _selectedSubject = value!;
                    _selectedTopic = 'All Topics'; // Reset topic when subject changes
                  });
                  _applyFilters();
                }),
                const SizedBox(height: 8),
                _buildFilterDropdown('Topic', _selectedTopic, _getTopicOptions(), (value) {
                  setState(() => _selectedTopic = value!);
                  _applyFilters();
                }),
                const SizedBox(height: 8),
                _buildFilterDropdown('Year', _selectedYear, _getYearOptions(), (value) {
                  setState(() => _selectedYear = value!);
                  _applyFilters();
                }),
              ],
            )
          else
            Column(
              children: [
                Row(
                  children: [
                    Expanded(
                      child: _buildFilterDropdown('Question Type', _selectedQuestionType, ['All Types', 'MCQ', 'Theory'], (value) {
                        setState(() => _selectedQuestionType = value!);
                        _applyFilters();
                      }),
                    ),
                    const SizedBox(width: 12),
                    Expanded(
                      child: _buildFilterDropdown('Subject', _selectedSubject, _getSubjectOptions(), (value) {
                        setState(() {
                          _selectedSubject = value!;
                          _selectedTopic = 'All Topics'; // Reset topic when subject changes
                        });
                        _applyFilters();
                      }),
                    ),
                  ],
                ),
                const SizedBox(height: 8),
                Row(
                  children: [
                    Expanded(
                      child: _buildFilterDropdown('Topic', _selectedTopic, _getTopicOptions(), (value) {
                        setState(() => _selectedTopic = value!);
                        _applyFilters();
                      }),
                    ),
                    const SizedBox(width: 12),
                    Expanded(
                      child: _buildFilterDropdown('Year', _selectedYear, _getYearOptions(), (value) {
                        setState(() => _selectedYear = value!);
                        _applyFilters();
                      }),
                    ),
                  ],
                ),
              ],
            ),
          const SizedBox(height: 16),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                'Found ${_filteredCollections.length} collections',
                style: GoogleFonts.montserrat(
                  color: Colors.grey[700],
                  fontSize: 14,
                  fontWeight: FontWeight.w500,
                ),
              ),
              if (_searchController.text.isNotEmpty || 
                  _selectedQuestionType != 'All Types' || 
                  _selectedSubject != 'All Subjects' || 
                  _selectedTopic != 'All Topics' ||
                  _selectedYear != 'All Years')
                TextButton.icon(
                  onPressed: () {
                    setState(() {
                      _searchController.clear();
                      _selectedQuestionType = 'All Types';
                      _selectedSubject = 'All Subjects';
                      _selectedTopic = 'All Topics';
                      _selectedYear = 'All Years';
                    });
                    _applyFilters();
                  },
                  icon: const Icon(Icons.clear, size: 16),
                  label: const Text('Clear Filters'),
                  style: TextButton.styleFrom(
                    foregroundColor: const Color(0xFFD62828),
                  ),
                ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildFilterDropdown(String label, String value, List<String> options, ValueChanged<String?> onChanged) {
    return DropdownButtonFormField<String>(
      value: value,
      onChanged: onChanged,
      decoration: InputDecoration(
        labelText: label,
        labelStyle: GoogleFonts.montserrat(color: Colors.grey[600]),
        filled: true,
        fillColor: const Color(0xFFF8FAFE),
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide.none,
        ),
        contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
      ),
      dropdownColor: Colors.white,
      style: GoogleFonts.montserrat(color: const Color(0xFF1A1E3F)),
      items: options.map((option) {
        return DropdownMenuItem(value: option, child: Text(option));
      }).toList(),
    );
  }

  List<String> _getSubjectOptions() {
    final subjects = _collections.map((c) => _formatSubjectName(c.subject)).toSet().toList();
    subjects.sort();
    return ['All Subjects', ...subjects];
  }

  List<String> _getYearOptions() {
    final years = _collections.map((c) => c.year).toSet().toList();
    years.sort((a, b) => b.compareTo(a)); // Most recent first
    return ['All Years', ...years];
  }

  List<String> _getTopicOptions() {
    // Get topics from collections matching current subject filter
    final relevantCollections = _selectedSubject == 'All Subjects'
        ? _collections
        : _collections.where((c) => _formatSubjectName(c.subject) == _selectedSubject).toList();
    
    final topicSet = <String>{};
    
    // Add collection-level topics (from saved collections like ICT/RME topics)
    for (final collection in relevantCollections) {
      if (collection.description != null && collection.description!.isNotEmpty) {
        // Skip generic descriptions, only add actual topic names
        final desc = collection.description!;
        if (!desc.startsWith('Practice') && desc.length > 5) {
          topicSet.add(desc);
        }
      }
    }
    
    // Also add question-level topics
    final questionTopics = relevantCollections
        .expand((c) => c.questions)
        .expand((q) => q.topics)
        .where((topic) {
          // Filter out years (4 digits), exam types (BECE, WASSCE), and subject names
          if (RegExp(r'^\d{4}$').hasMatch(topic)) return false; // Years
          if (topic.toUpperCase() == 'BECE' || topic.toUpperCase() == 'WASSCE') return false;
          if (topic.toUpperCase() == 'ICT' || topic == 'Information And Communication Technology') return false;
          return true;
        });
    
    topicSet.addAll(questionTopics);
    
    final topics = topicSet.toList();
    topics.sort();
    return ['All Topics', ...topics];
  }

  Widget _buildEmptyState() {
    return Container(
      padding: const EdgeInsets.all(48),
      child: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(Icons.folder_open, size: 64, color: Colors.grey[300]),
            const SizedBox(height: 16),
            Text(
              'No collections found',
              style: GoogleFonts.playfairDisplay(
                color: const Color(0xFF1A1E3F),
                fontSize: 18,
                fontWeight: FontWeight.bold,
              ),
            ),
            const SizedBox(height: 8),
            Text(
              'Try adjusting your filters',
              style: GoogleFonts.montserrat(color: Colors.grey[600], fontSize: 14),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildCollectionsList(bool isSmallScreen) {
    return Container(
      padding: EdgeInsets.symmetric(
        horizontal: isSmallScreen ? 16 : 24,
        vertical: 8,
      ),
      child: Column(
        children: [
          // Collections grid / list
          isSmallScreen
              ? Column(
                  children: _filteredCollections.map((collection) {
                    return _buildCollectionCard(collection, isSmallScreen);
                  }).toList(),
                )
              : GridView.builder(
                  shrinkWrap: true,
                  physics: const NeverScrollableScrollPhysics(),
                  gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
                    crossAxisCount: 2, // 2 cards per line
                    crossAxisSpacing: 16,
                    mainAxisSpacing: 16,
                    childAspectRatio: 2.1, // 15% height reduction (was 1.8)
                  ),
                  itemCount: _filteredCollections.length,
                  itemBuilder: (context, index) {
                    return _buildCollectionCard(_filteredCollections[index], isSmallScreen);
                  },
                ),

          const SizedBox(height: 12),

          // Load More Button (if more collections available)
          if (_hasMoreCollections && !_isLoadingMore)
            Padding(
              padding: const EdgeInsets.all(16),
              child: ElevatedButton(
                onPressed: _loadMoreCollections,
                style: ElevatedButton.styleFrom(
                  backgroundColor: const Color(0xFFD62828),
                  foregroundColor: Colors.white,
                  padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 16),
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(12),
                  ),
                ),
                child: const Text('Load More Collections'),
              ),
            ),

          // Loading indicator for background loading
          if (_isLoadingMore)
            const Padding(
              padding: EdgeInsets.all(16),
              child: CircularProgressIndicator(color: Color(0xFFD62828)),
            ),

          // Legacy pagination controls (for filtered results if needed)
          if (_filteredCollections.length > _pageSize && !_hasMoreCollections)
            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                TextButton.icon(
                  onPressed: _currentPage > 0 ? () => setState(() => _currentPage--) : null,
                  icon: const Icon(Icons.chevron_left),
                  label: const Text('Previous'),
                ),
                const SizedBox(width: 12),
                Text('Page ${_currentPage + 1} of ${(_filteredCollections.length / _pageSize).ceil()}',
                     style: GoogleFonts.montserrat()),
                const SizedBox(width: 12),
                TextButton.icon(
                  onPressed: _currentPage < (_filteredCollections.length / _pageSize).ceil() - 1
                      ? () => setState(() => _currentPage++)
                      : null,
                  icon: const Icon(Icons.chevron_right),
                  label: const Text('Next'),
                ),
              ],
            ),
        ],
      ),
    );
  }

  Widget _buildCollectionCard(QuestionCollection collection, bool isSmallScreen) {
    return Container(
      margin: isSmallScreen ? const EdgeInsets.only(bottom: 16) : EdgeInsets.zero,
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.05),
            blurRadius: 10,
            offset: const Offset(0, 2),
          ),
        ],
      ),
      child: Padding(
        padding: EdgeInsets.all(isSmallScreen ? 16 : 20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                  decoration: BoxDecoration(
                    color: const Color(0xFFD62828),
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: Text(
                    collection.examType.name.toUpperCase(),
                    style: GoogleFonts.montserrat(
                      color: Colors.white,
                      fontSize: 12,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ),
                const SizedBox(width: 8),
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                  decoration: BoxDecoration(
                    color: const Color(0xFFF8FAFE),
                    borderRadius: BorderRadius.circular(8),
                    border: Border.all(color: const Color(0xFF1A1E3F).withValues(alpha: 0.1)),
                  ),
                  child: Text(
                    collection.year,
                    style: GoogleFonts.montserrat(
                      color: const Color(0xFF1A1E3F),
                      fontSize: 12,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ),
              ],
            ),
            const SizedBox(height: 12),
            Text(
              collection.title.isNotEmpty ? collection.title : collection.displayName,
              style: GoogleFonts.playfairDisplay(
                color: const Color(0xFF1A1E3F),
                fontSize: isSmallScreen ? 18 : 20,
                fontWeight: FontWeight.bold,
              ),
            ),
            const SizedBox(height: 8),
            Row(
              children: [
                Icon(Icons.quiz, size: 16, color: Colors.grey[600]),
                const SizedBox(width: 4),
                Text(
                  '${collection.questionCount} Questions',
                  style: GoogleFonts.montserrat(
                    color: Colors.grey[600],
                    fontSize: 14,
                  ),
                ),
              ],
            ),
            const SizedBox(height: 16),
            // Randomize Toggle and Start Quiz Button - responsive layout
            isSmallScreen
                ? Column(
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    children: [
                      // Randomize Toggle (Mobile - full width)
                      Row(
                        children: [
                          Switch(
                            value: _randomizeQuestions,
                            onChanged: (value) => setState(() => _randomizeQuestions = value),
                            activeColor: const Color(0xFFD62828),
                          ),
                          const SizedBox(width: 8),
                          Expanded(
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Text(
                                  'Randomize Questions',
                                  style: GoogleFonts.montserrat(
                                    fontWeight: FontWeight.w500,
                                    fontSize: 14,
                                    color: const Color(0xFF1A1E3F),
                                  ),
                                ),
                                Text(
                                  'Questions will appear in random order',
                                  style: GoogleFonts.montserrat(
                                    fontSize: 12,
                                    color: Colors.grey[600],
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ],
                      ),
                      const SizedBox(height: 12),
                      // Question Count Selector (Mobile - full width)
                      _buildQuestionCountSelector(collection, isSmallScreen),
                      const SizedBox(height: 12),
                      // Start Quiz Button (Mobile - full width)
                      _buildActionButton(
                        icon: collection.questionType == QuestionType.essay ? Icons.edit_note : Icons.play_arrow,
                        label: collection.questionType == QuestionType.essay ? 'Start' : 'Start Quiz',
                        onPressed: () => _startQuiz(collection),
                        isPrimary: true,
                      ),
                    ],
                  )
                : Column(
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    children: [
                      Row(
                        children: [
                          // Randomize Questions Toggle (Desktop - Left side)
                          Expanded(
                            flex: 2,
                            child: Row(
                              children: [
                                Switch(
                                  value: _randomizeQuestions,
                                  onChanged: (value) => setState(() => _randomizeQuestions = value),
                                  activeColor: const Color(0xFFD62828),
                                ),
                                const SizedBox(width: 8),
                                Expanded(
                                  child: Column(
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    children: [
                                      Text(
                                        'Randomize',
                                        style: GoogleFonts.montserrat(
                                          fontWeight: FontWeight.w500,
                                          fontSize: 13,
                                          color: const Color(0xFF1A1E3F),
                                        ),
                                      ),
                                      Text(
                                        'Random order',
                                        style: GoogleFonts.montserrat(
                                          fontSize: 11,
                                          color: Colors.grey[600],
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ],
                            ),
                          ),
                          const SizedBox(width: 12),
                          // Start Quiz Button (Desktop - Right side, 20% larger than before)
                          Flexible(
                            child: FractionallySizedBox(
                              widthFactor: 0.84, // 20% increase from 0.7
                              child: _buildActionButton(
                                icon: collection.questionType == QuestionType.essay ? Icons.edit_note : Icons.play_arrow,
                                label: collection.questionType == QuestionType.essay ? 'Start' : 'Start Quiz',
                                onPressed: () => _startQuiz(collection),
                                isPrimary: true,
                              ),
                            ),
                          ),
                        ],
                      ),
                      const SizedBox(height: 8),
                      // Question Count Selector (Desktop - full width below)
                      _buildQuestionCountSelector(collection, isSmallScreen),
                    ],
                  ),
          ],
        ),
      ),
    );
  }

  Widget _buildActionButton({
    required IconData icon,
    required String label,
    required VoidCallback onPressed,
    required bool isPrimary,
  }) {
    return ElevatedButton.icon(
      onPressed: onPressed,
      icon: Icon(icon, size: 20),
      label: Text(label),
      style: ElevatedButton.styleFrom(
        backgroundColor: isPrimary ? const Color(0xFF2ECC71) : const Color(0xFF1A1E3F), // Uriel Blue
        foregroundColor: Colors.white, // White text for both buttons
        padding: const EdgeInsets.symmetric(vertical: 14, horizontal: 16),
        elevation: 0,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(12),
        ),
      ),
    );
  }

  Widget _buildQuestionCountSelector(QuestionCollection collection, bool isSmallScreen) {
    // Get available counts based on collection size
    final availableCounts = [10, 20, 40].where((count) => count <= collection.questionCount).toList();
    
    // If collection has fewer questions, add small count
    if (collection.questionCount < 10) {
      availableCounts.clear();
      availableCounts.add(collection.questionCount);
    }
    
    // Add "All" as last option if collection has more than 40 questions
    final showAllOption = collection.questionCount > 40;
    
    // Get current selection or default to first available count
    final currentCount = _selectedQuestionCounts[collection.id] ?? availableCounts.first;
    
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
      decoration: BoxDecoration(
        color: const Color(0xFFF8FAFE),
        borderRadius: BorderRadius.circular(8),
        border: Border.all(color: const Color(0xFF1A1E3F).withValues(alpha: 0.1)),
      ),
      child: Row(
        children: [
          Icon(Icons.format_list_numbered, size: 16, color: Colors.grey[600]),
          const SizedBox(width: 8),
          Text(
            'Questions:',
            style: GoogleFonts.montserrat(
              fontSize: 13,
              fontWeight: FontWeight.w500,
              color: const Color(0xFF1A1E3F),
            ),
          ),
          const SizedBox(width: 12),
          Expanded(
            child: Row(
              mainAxisAlignment: MainAxisAlignment.end,
              children: [
                ...availableCounts.map((count) => Padding(
                  padding: const EdgeInsets.only(left: 8),
                  child: _buildCountChip(
                    label: count.toString(),
                    isSelected: currentCount == count,
                    onTap: () {
                      setState(() {
                        _selectedQuestionCounts[collection.id] = count;
                      });
                    },
                  ),
                )),
                if (showAllOption)
                  Padding(
                    padding: const EdgeInsets.only(left: 8),
                    child: _buildCountChip(
                      label: 'All',
                      isSelected: currentCount == collection.questionCount,
                      onTap: () {
                        setState(() {
                          _selectedQuestionCounts[collection.id] = collection.questionCount;
                        });
                      },
                    ),
                  ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildCountChip({
    required String label,
    required bool isSelected,
    required VoidCallback onTap,
  }) {
    return InkWell(
      onTap: onTap,
      borderRadius: BorderRadius.circular(6),
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
        decoration: BoxDecoration(
          color: isSelected ? const Color(0xFFD62828) : Colors.white,
          borderRadius: BorderRadius.circular(6),
          border: Border.all(
            color: isSelected ? const Color(0xFFD62828) : Colors.grey[300]!,
            width: 1.5,
          ),
        ),
        child: Text(
          label,
          style: GoogleFonts.montserrat(
            fontSize: 12,
            fontWeight: FontWeight.w600,
            color: isSelected ? Colors.white : const Color(0xFF1A1E3F),
          ),
        ),
      ),
    );
  }

  void _startQuiz(QuestionCollection collection) {
    // Get selected question count or default
    final selectedCount = _selectedQuestionCounts[collection.id] ?? 
        ([10, 20, 40].where((c) => c <= collection.questionCount).firstOrNull ?? collection.questionCount);
    
    // Get questions (randomize if enabled)
    var questions = _randomizeQuestions
        ? (collection.questions.toList()..shuffle())
        : collection.questions;
    
    // Limit to selected count
    if (selectedCount < questions.length) {
      questions = questions.take(selectedCount).toList();
    }

    // Check if this is a theory/essay collection
    if (collection.questionType == QuestionType.essay) {
      // Route to theory questions list
      Navigator.push(
        context,
        MaterialPageRoute(
          builder: (context) => TheoryYearQuestionsList(
            subject: _formatSubjectName(collection.subject),
            year: int.parse(collection.year),
          ),
        ),
      );
    } else {
      // Start MCQ quiz immediately, bypassing quiz setup page
      Navigator.push(
        context,
        MaterialPageRoute(
          builder: (context) => QuizTakerPage(
            subject: _formatSubjectName(collection.subject),
            examType: collection.examType.name.toUpperCase(),
            level: 'JHS 3', // Default to JHS 3 for BECE
            questionCount: questions.length,
            randomizeQuestions: false, // Already randomized if needed
            preloadedQuestions: questions, // Pass limited questions
          ),
        ),
      );
    }
  }
}
